### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Recillah-Khamala** [Recillah-Khamala/Catalogue_Of_My_Things#43]
In this milestone, we have done the below.

- Our repository project link is as below
  - https://github.com/Recillah-Khamala/Catalogue_Of_My_Things/projects/1
- Our team is composed of 3 members and we have assigned the tasks among ourselves as below
  - Team member # 1 @Recillah-Khamala 
  - Team member # 2 @Kaweesi-Matia 
  - Team member # 3 @tashisrael

**Comment by omarsalem7** [comment]
Hi team 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- Kanban board created ✔️
- Each card assign to a team member ✔️

## Required Changes ♻️
- [ ] Kindly add a description for cards related to @Kaweesi-Matia 
- [ ] Kindly consider adding the number of points in the [Xpt] prefix for each task. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brytebee** [comment]
Hi, Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
